-- generated by elm_rs


module Api.Types exposing (..)

import Dict exposing (Dict)
import Http
import Json.Decode
import Json.Encode
import Url.Builder


resultEncoder : (e -> Json.Encode.Value) -> (t -> Json.Encode.Value) -> (Result e t -> Json.Encode.Value)
resultEncoder errEncoder okEncoder enum =
    case enum of
        Ok inner ->
            Json.Encode.object [ ( "Ok", okEncoder inner ) ]

        Err inner ->
            Json.Encode.object [ ( "Err", errEncoder inner ) ]


resultDecoder : Json.Decode.Decoder e -> Json.Decode.Decoder t -> Json.Decode.Decoder (Result e t)
resultDecoder errDecoder okDecoder =
    Json.Decode.oneOf
        [ Json.Decode.map Ok (Json.Decode.field "Ok" okDecoder)
        , Json.Decode.map Err (Json.Decode.field "Err" errDecoder)
        ]


type alias HelloResponse =
    { message : String
    }


helloResponseEncoder : HelloResponse -> Json.Encode.Value
helloResponseEncoder struct =
    Json.Encode.object
        [ ( "message", Json.Encode.string struct.message )
        ]


helloResponseDecoder : Json.Decode.Decoder HelloResponse
helloResponseDecoder =
    Json.Decode.succeed HelloResponse
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "message" Json.Decode.string))
