-- generated by elm_rs


module Api.Types exposing (..)

import Dict exposing (Dict)
import Http
import Json.Decode
import Json.Encode
import Url.Builder


resultEncoder : (e -> Json.Encode.Value) -> (t -> Json.Encode.Value) -> (Result e t -> Json.Encode.Value)
resultEncoder errEncoder okEncoder enum =
    case enum of
        Ok inner ->
            Json.Encode.object [ ( "Ok", okEncoder inner ) ]

        Err inner ->
            Json.Encode.object [ ( "Err", errEncoder inner ) ]


resultDecoder : Json.Decode.Decoder e -> Json.Decode.Decoder t -> Json.Decode.Decoder (Result e t)
resultDecoder errDecoder okDecoder =
    Json.Decode.oneOf
        [ Json.Decode.map Ok (Json.Decode.field "Ok" okDecoder)
        , Json.Decode.map Err (Json.Decode.field "Err" errDecoder)
        ]


type alias HelloResponse =
    { message : String
    }


helloResponseEncoder : HelloResponse -> Json.Encode.Value
helloResponseEncoder struct =
    Json.Encode.object
        [ ( "message", Json.Encode.string struct.message )
        ]


type alias LoginRequest =
    { email : String
    , password : String
    }


loginRequestEncoder : LoginRequest -> Json.Encode.Value
loginRequestEncoder struct =
    Json.Encode.object
        [ ( "email", Json.Encode.string struct.email )
        , ( "password", Json.Encode.string struct.password )
        ]


type alias UserResponse =
    { id : String
    , email : String
    , name : Maybe String
    , isAdmin : Bool
    }


userResponseEncoder : UserResponse -> Json.Encode.Value
userResponseEncoder struct =
    Json.Encode.object
        [ ( "id", Json.Encode.string struct.id )
        , ( "email", Json.Encode.string struct.email )
        , ( "name", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.name )
        , ( "is_admin", Json.Encode.bool struct.isAdmin )
        ]


type alias MeResponse =
    { id : String
    , email : String
    , name : Maybe String
    , isAdmin : Bool
    , permissions : List String
    , totpEnabled : Bool
    , companyName : String
    }


meResponseEncoder : MeResponse -> Json.Encode.Value
meResponseEncoder struct =
    Json.Encode.object
        [ ( "id", Json.Encode.string struct.id )
        , ( "email", Json.Encode.string struct.email )
        , ( "name", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.name )
        , ( "is_admin", Json.Encode.bool struct.isAdmin )
        , ( "permissions", Json.Encode.list Json.Encode.string struct.permissions )
        , ( "totp_enabled", Json.Encode.bool struct.totpEnabled )
        , ( "company_name", Json.Encode.string struct.companyName )
        ]


type AuthError
    = InvalidCredentials
    | AccountDeactivated
    | NotSignedIn
    | InvalidCode


authErrorEncoder : AuthError -> Json.Encode.Value
authErrorEncoder enum =
    case enum of
        InvalidCredentials ->
            Json.Encode.string "InvalidCredentials"

        AccountDeactivated ->
            Json.Encode.string "AccountDeactivated"

        NotSignedIn ->
            Json.Encode.string "NotSignedIn"

        InvalidCode ->
            Json.Encode.string "InvalidCode"


type alias CreateUser =
    { email : String
    , password : String
    , name : Maybe String
    , isAdmin : Bool
    }


createUserEncoder : CreateUser -> Json.Encode.Value
createUserEncoder struct =
    Json.Encode.object
        [ ( "email", Json.Encode.string struct.email )
        , ( "password", Json.Encode.string struct.password )
        , ( "name", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.name )
        , ( "is_admin", Json.Encode.bool struct.isAdmin )
        ]


type alias CreateRole =
    { name : String
    , description : Maybe String
    }


createRoleEncoder : CreateRole -> Json.Encode.Value
createRoleEncoder struct =
    Json.Encode.object
        [ ( "name", Json.Encode.string struct.name )
        , ( "description", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.description )
        ]


type alias RoleResponse =
    { id : String
    , name : String
    , description : Maybe String
    }


roleResponseEncoder : RoleResponse -> Json.Encode.Value
roleResponseEncoder struct =
    Json.Encode.object
        [ ( "id", Json.Encode.string struct.id )
        , ( "name", Json.Encode.string struct.name )
        , ( "description", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.description )
        ]


type alias PermissionBody =
    { permission : String
    }


permissionBodyEncoder : PermissionBody -> Json.Encode.Value
permissionBodyEncoder struct =
    Json.Encode.object
        [ ( "permission", Json.Encode.string struct.permission )
        ]


type alias PermissionsBody =
    { permissions : List String
    }


permissionsBodyEncoder : PermissionsBody -> Json.Encode.Value
permissionsBodyEncoder struct =
    Json.Encode.object
        [ ( "permissions", Json.Encode.list Json.Encode.string struct.permissions )
        ]


type alias RoleBody =
    { roleId : String
    }


roleBodyEncoder : RoleBody -> Json.Encode.Value
roleBodyEncoder struct =
    Json.Encode.object
        [ ( "role_id", Json.Encode.string struct.roleId )
        ]


type alias PermissionInfo =
    { name : String
    , parent : Maybe String
    }


permissionInfoEncoder : PermissionInfo -> Json.Encode.Value
permissionInfoEncoder struct =
    Json.Encode.object
        [ ( "name", Json.Encode.string struct.name )
        , ( "parent", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.parent )
        ]


type ServerMessage
    = Snapshot { online : List String }
    | Online { userId : String }
    | Offline { userId : String }
    | Broadcast { from : String, text : String }


serverMessageEncoder : ServerMessage -> Json.Encode.Value
serverMessageEncoder enum =
    case enum of
        Snapshot { online } ->
            Json.Encode.object [ ( "Snapshot", Json.Encode.object [ ( "online", Json.Encode.list Json.Encode.string online ) ] ) ]

        Online { userId } ->
            Json.Encode.object [ ( "Online", Json.Encode.object [ ( "user_id", Json.Encode.string userId ) ] ) ]

        Offline { userId } ->
            Json.Encode.object [ ( "Offline", Json.Encode.object [ ( "user_id", Json.Encode.string userId ) ] ) ]

        Broadcast { from, text } ->
            Json.Encode.object [ ( "Broadcast", Json.Encode.object [ ( "from", Json.Encode.string from ), ( "text", Json.Encode.string text ) ] ) ]


type ClientMessage
    = SendBroadcast { text : String }


clientMessageEncoder : ClientMessage -> Json.Encode.Value
clientMessageEncoder enum =
    case enum of
        SendBroadcast { text } ->
            Json.Encode.object [ ( "SendBroadcast", Json.Encode.object [ ( "text", Json.Encode.string text ) ] ) ]


type LoginResponse
    = Authenticated { user : UserResponse }
    | TotpRequired


loginResponseEncoder : LoginResponse -> Json.Encode.Value
loginResponseEncoder enum =
    case enum of
        Authenticated { user } ->
            Json.Encode.object [ ( "Authenticated", Json.Encode.object [ ( "user", userResponseEncoder user ) ] ) ]

        TotpRequired ->
            Json.Encode.string "TotpRequired"


type alias ChangePassword =
    { currentPassword : String
    , newPassword : String
    }


changePasswordEncoder : ChangePassword -> Json.Encode.Value
changePasswordEncoder struct =
    Json.Encode.object
        [ ( "current_password", Json.Encode.string struct.currentPassword )
        , ( "new_password", Json.Encode.string struct.newPassword )
        ]


type PasswordError
    = IncorrectPassword
    | PasswordTooShort


passwordErrorEncoder : PasswordError -> Json.Encode.Value
passwordErrorEncoder enum =
    case enum of
        IncorrectPassword ->
            Json.Encode.string "IncorrectPassword"

        PasswordTooShort ->
            Json.Encode.string "PasswordTooShort"


type alias TotpSetup =
    { secret : String
    , otpauthUrl : String
    , qrPng : String
    }


totpSetupEncoder : TotpSetup -> Json.Encode.Value
totpSetupEncoder struct =
    Json.Encode.object
        [ ( "secret", Json.Encode.string struct.secret )
        , ( "otpauth_url", Json.Encode.string struct.otpauthUrl )
        , ( "qr_png", Json.Encode.string struct.qrPng )
        ]


type alias TotpCode =
    { code : String
    }


totpCodeEncoder : TotpCode -> Json.Encode.Value
totpCodeEncoder struct =
    Json.Encode.object
        [ ( "code", Json.Encode.string struct.code )
        ]


type alias TotpConfirm =
    { secret : String
    , code : String
    }


totpConfirmEncoder : TotpConfirm -> Json.Encode.Value
totpConfirmEncoder struct =
    Json.Encode.object
        [ ( "secret", Json.Encode.string struct.secret )
        , ( "code", Json.Encode.string struct.code )
        ]


type alias TotpDisable =
    { password : String
    }


totpDisableEncoder : TotpDisable -> Json.Encode.Value
totpDisableEncoder struct =
    Json.Encode.object
        [ ( "password", Json.Encode.string struct.password )
        ]


type SettingKind
    = Bool
    | Text


settingKindEncoder : SettingKind -> Json.Encode.Value
settingKindEncoder enum =
    case enum of
        Bool ->
            Json.Encode.string "Bool"

        Text ->
            Json.Encode.string "Text"


type alias SettingInfo =
    { name : String
    , value : String
    , kind : SettingKind
    }


settingInfoEncoder : SettingInfo -> Json.Encode.Value
settingInfoEncoder struct =
    Json.Encode.object
        [ ( "name", Json.Encode.string struct.name )
        , ( "value", Json.Encode.string struct.value )
        , ( "kind", settingKindEncoder struct.kind )
        ]


type alias SettingUpdate =
    { name : String
    , value : String
    }


settingUpdateEncoder : SettingUpdate -> Json.Encode.Value
settingUpdateEncoder struct =
    Json.Encode.object
        [ ( "name", Json.Encode.string struct.name )
        , ( "value", Json.Encode.string struct.value )
        ]


type alias SettingsBody =
    { settings : List SettingUpdate
    }


settingsBodyEncoder : SettingsBody -> Json.Encode.Value
settingsBodyEncoder struct =
    Json.Encode.object
        [ ( "settings", Json.Encode.list settingUpdateEncoder struct.settings )
        ]


type alias PublicConfig =
    { companyName : String
    , registrationEnabled : Bool
    }


publicConfigEncoder : PublicConfig -> Json.Encode.Value
publicConfigEncoder struct =
    Json.Encode.object
        [ ( "company_name", Json.Encode.string struct.companyName )
        , ( "registration_enabled", Json.Encode.bool struct.registrationEnabled )
        ]


type alias RegisterRequest =
    { email : String
    , password : String
    , name : Maybe String
    }


registerRequestEncoder : RegisterRequest -> Json.Encode.Value
registerRequestEncoder struct =
    Json.Encode.object
        [ ( "email", Json.Encode.string struct.email )
        , ( "password", Json.Encode.string struct.password )
        , ( "name", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.name )
        ]


type RegistrationError
    = RegistrationDisabled
    | EmailTaken
    | InvalidEmail
    | WeakPassword


registrationErrorEncoder : RegistrationError -> Json.Encode.Value
registrationErrorEncoder enum =
    case enum of
        RegistrationDisabled ->
            Json.Encode.string "RegistrationDisabled"

        EmailTaken ->
            Json.Encode.string "EmailTaken"

        InvalidEmail ->
            Json.Encode.string "InvalidEmail"

        WeakPassword ->
            Json.Encode.string "WeakPassword"


type alias UserPage =
    { items : List UserResponse
    , total : Int
    , page : Int
    , perPage : Int
    }


userPageEncoder : UserPage -> Json.Encode.Value
userPageEncoder struct =
    Json.Encode.object
        [ ( "items", Json.Encode.list userResponseEncoder struct.items )
        , ( "total", Json.Encode.int struct.total )
        , ( "page", Json.Encode.int struct.page )
        , ( "per_page", Json.Encode.int struct.perPage )
        ]


type alias RolePage =
    { items : List RoleResponse
    , total : Int
    , page : Int
    , perPage : Int
    }


rolePageEncoder : RolePage -> Json.Encode.Value
rolePageEncoder struct =
    Json.Encode.object
        [ ( "items", Json.Encode.list roleResponseEncoder struct.items )
        , ( "total", Json.Encode.int struct.total )
        , ( "page", Json.Encode.int struct.page )
        , ( "per_page", Json.Encode.int struct.perPage )
        ]


helloResponseDecoder : Json.Decode.Decoder HelloResponse
helloResponseDecoder =
    Json.Decode.succeed HelloResponse
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "message" Json.Decode.string))


loginRequestDecoder : Json.Decode.Decoder LoginRequest
loginRequestDecoder =
    Json.Decode.succeed LoginRequest
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "email" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "password" Json.Decode.string))


userResponseDecoder : Json.Decode.Decoder UserResponse
userResponseDecoder =
    Json.Decode.succeed UserResponse
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "email" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "is_admin" Json.Decode.bool))


meResponseDecoder : Json.Decode.Decoder MeResponse
meResponseDecoder =
    Json.Decode.succeed MeResponse
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "email" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "is_admin" Json.Decode.bool))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "permissions" (Json.Decode.list Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "totp_enabled" Json.Decode.bool))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "company_name" Json.Decode.string))


authErrorDecoder : Json.Decode.Decoder AuthError
authErrorDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "InvalidCredentials" ->
                            Json.Decode.succeed InvalidCredentials

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "AccountDeactivated" ->
                            Json.Decode.succeed AccountDeactivated

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "NotSignedIn" ->
                            Json.Decode.succeed NotSignedIn

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "InvalidCode" ->
                            Json.Decode.succeed InvalidCode

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


createUserDecoder : Json.Decode.Decoder CreateUser
createUserDecoder =
    Json.Decode.succeed CreateUser
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "email" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "password" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "is_admin" Json.Decode.bool))


createRoleDecoder : Json.Decode.Decoder CreateRole
createRoleDecoder =
    Json.Decode.succeed CreateRole
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.nullable Json.Decode.string)))


roleResponseDecoder : Json.Decode.Decoder RoleResponse
roleResponseDecoder =
    Json.Decode.succeed RoleResponse
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.nullable Json.Decode.string)))


permissionBodyDecoder : Json.Decode.Decoder PermissionBody
permissionBodyDecoder =
    Json.Decode.succeed PermissionBody
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "permission" Json.Decode.string))


permissionsBodyDecoder : Json.Decode.Decoder PermissionsBody
permissionsBodyDecoder =
    Json.Decode.succeed PermissionsBody
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "permissions" (Json.Decode.list Json.Decode.string)))


roleBodyDecoder : Json.Decode.Decoder RoleBody
roleBodyDecoder =
    Json.Decode.succeed RoleBody
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "role_id" Json.Decode.string))


permissionInfoDecoder : Json.Decode.Decoder PermissionInfo
permissionInfoDecoder =
    Json.Decode.succeed PermissionInfo
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "parent" (Json.Decode.nullable Json.Decode.string)))


serverMessageDecoder : Json.Decode.Decoder ServerMessage
serverMessageDecoder =
    let
        elmRsConstructSnapshot online =
            Snapshot { online = online }

        elmRsConstructOnline userId =
            Online { userId = userId }

        elmRsConstructOffline userId =
            Offline { userId = userId }

        elmRsConstructBroadcast from text =
            Broadcast { from = from, text = text }
    in
    Json.Decode.oneOf
        [ Json.Decode.field "Snapshot" (Json.Decode.succeed elmRsConstructSnapshot |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "online" (Json.Decode.list Json.Decode.string))))
        , Json.Decode.field "Online" (Json.Decode.succeed elmRsConstructOnline |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "user_id" Json.Decode.string)))
        , Json.Decode.field "Offline" (Json.Decode.succeed elmRsConstructOffline |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "user_id" Json.Decode.string)))
        , Json.Decode.field "Broadcast" (Json.Decode.succeed elmRsConstructBroadcast |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "from" Json.Decode.string)) |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "text" Json.Decode.string)))
        ]


clientMessageDecoder : Json.Decode.Decoder ClientMessage
clientMessageDecoder =
    let
        elmRsConstructSendBroadcast text =
            SendBroadcast { text = text }
    in
    Json.Decode.oneOf
        [ Json.Decode.field "SendBroadcast" (Json.Decode.succeed elmRsConstructSendBroadcast |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "text" Json.Decode.string)))
        ]


loginResponseDecoder : Json.Decode.Decoder LoginResponse
loginResponseDecoder =
    let
        elmRsConstructAuthenticated user =
            Authenticated { user = user }
    in
    Json.Decode.oneOf
        [ Json.Decode.field "Authenticated" (Json.Decode.succeed elmRsConstructAuthenticated |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "user" userResponseDecoder)))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "TotpRequired" ->
                            Json.Decode.succeed TotpRequired

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


changePasswordDecoder : Json.Decode.Decoder ChangePassword
changePasswordDecoder =
    Json.Decode.succeed ChangePassword
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "current_password" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "new_password" Json.Decode.string))


passwordErrorDecoder : Json.Decode.Decoder PasswordError
passwordErrorDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "IncorrectPassword" ->
                            Json.Decode.succeed IncorrectPassword

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "PasswordTooShort" ->
                            Json.Decode.succeed PasswordTooShort

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


totpSetupDecoder : Json.Decode.Decoder TotpSetup
totpSetupDecoder =
    Json.Decode.succeed TotpSetup
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "secret" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "otpauth_url" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "qr_png" Json.Decode.string))


totpCodeDecoder : Json.Decode.Decoder TotpCode
totpCodeDecoder =
    Json.Decode.succeed TotpCode
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "code" Json.Decode.string))


totpConfirmDecoder : Json.Decode.Decoder TotpConfirm
totpConfirmDecoder =
    Json.Decode.succeed TotpConfirm
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "secret" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "code" Json.Decode.string))


totpDisableDecoder : Json.Decode.Decoder TotpDisable
totpDisableDecoder =
    Json.Decode.succeed TotpDisable
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "password" Json.Decode.string))


settingKindDecoder : Json.Decode.Decoder SettingKind
settingKindDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Bool" ->
                            Json.Decode.succeed Bool

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Text" ->
                            Json.Decode.succeed Text

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


settingInfoDecoder : Json.Decode.Decoder SettingInfo
settingInfoDecoder =
    Json.Decode.succeed SettingInfo
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "value" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "kind" settingKindDecoder))


settingUpdateDecoder : Json.Decode.Decoder SettingUpdate
settingUpdateDecoder =
    Json.Decode.succeed SettingUpdate
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "value" Json.Decode.string))


settingsBodyDecoder : Json.Decode.Decoder SettingsBody
settingsBodyDecoder =
    Json.Decode.succeed SettingsBody
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "settings" (Json.Decode.list settingUpdateDecoder)))


publicConfigDecoder : Json.Decode.Decoder PublicConfig
publicConfigDecoder =
    Json.Decode.succeed PublicConfig
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "company_name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "registration_enabled" Json.Decode.bool))


registerRequestDecoder : Json.Decode.Decoder RegisterRequest
registerRequestDecoder =
    Json.Decode.succeed RegisterRequest
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "email" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "password" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.nullable Json.Decode.string)))


registrationErrorDecoder : Json.Decode.Decoder RegistrationError
registrationErrorDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "RegistrationDisabled" ->
                            Json.Decode.succeed RegistrationDisabled

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "EmailTaken" ->
                            Json.Decode.succeed EmailTaken

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "InvalidEmail" ->
                            Json.Decode.succeed InvalidEmail

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "WeakPassword" ->
                            Json.Decode.succeed WeakPassword

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


userPageDecoder : Json.Decode.Decoder UserPage
userPageDecoder =
    Json.Decode.succeed UserPage
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "items" (Json.Decode.list userResponseDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "total" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "page" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "per_page" Json.Decode.int))


rolePageDecoder : Json.Decode.Decoder RolePage
rolePageDecoder =
    Json.Decode.succeed RolePage
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "items" (Json.Decode.list roleResponseDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "total" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "page" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "per_page" Json.Decode.int))
